# yaml-language-server: $schema=none
namespace: zjleblanc
name: utils
version: 0.0.0-semantic-version
readme: README.md
authors:
  - Zach LeBlanc <@zjleblanc>

description: Utility plugins for Ansible automation workflows
license_file: LICENSE

tags:
  - utilities
  - utils
  - tools

dependencies:
  community.general: ">=5.0.0"

repository: https://github.com/zjleblanc/zjleblanc.utils
documentation: https://github.com/zjleblanc/zjleblanc.utils/blob/master/README.md
homepage: https://github.com/zjleblanc/zjleblanc.utils
issues: https://github.com/zjleblanc/zjleblanc.utils/issues

build_ignore:
  - .venv
  - .gitignore
  - ansible.cfg
  - collections
  - docs
  - tests
