---
- name: Generate Let's Encrypt account key
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_account_key }}"

- name: Remove existing ssl files
  loop:
    - "{{ letsencrypt_keys_dir }}/{{ letsencrypt_domain_name }}.key"
    - "{{ letsencrypt_csrs_dir }}/{{ letsencrypt_domain_name }}.csr"
    - "{{ letsencrypt_certs_dir }}/{{ letsencrypt_domain_name }}.pem"
    - "{{ letsencrypt_certs_dir }}/fullchain_{{ letsencrypt_domain_name }}.pem"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent

- name: Generate Let's Encrypt private key
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_keys_dir }}/{{ letsencrypt_domain_name }}.key"
    mode: "{{ letsencrypt_keys_mode | default(omit) }}"

- name: Generate Let's Encrypt CSR
  community.crypto.openssl_csr:
    path: "{{ letsencrypt_csrs_dir }}/{{ letsencrypt_domain_name }}.csr"
    privatekey_path: "{{ letsencrypt_keys_dir }}/{{ letsencrypt_domain_name }}.key"
    common_name: "{{ letsencrypt_domain_name }}"

- name: Begin Let's Encrypt challenges
  register: r_acme_challenge
  community.crypto.acme_certificate:
    acme_directory: "{{ letsencrypt_directory }}"
    acme_version: "{{ letsencrypt_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ letsencrypt_email }}"
    terms_agreed: 1
    challenge: "{{ letsencrypt_challenge_type | replace('_','-') }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ letsencrypt_domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ letsencrypt_domain_name }}.pem"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ letsencrypt_domain_name }}.pem"
    remaining_days: 91

- name: "Implement challenge | {{ letsencrypt_challenge_type }}"
  ansible.builtin.include_tasks:
    file: "{{ letsencrypt_challenge_type }}.yml" 

- name: Complete Let's Encrypt challenges
  community.crypto.acme_certificate:
    acme_directory: "{{ letsencrypt_directory }}"
    acme_version: "{{ letsencrypt_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ letsencrypt_email }}"
    challenge: "{{ letsencrypt_challenge_type | replace('_','-') }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ letsencrypt_domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ letsencrypt_domain_name }}.pem"
    chain_dest: "{{ letsencrypt_certs_dir }}/chain_{{ letsencrypt_domain_name }}.pem"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ letsencrypt_domain_name }}.pem"
    data: "{{ r_acme_challenge }}"

- name: Cleanup dns-01 challenge implementation
  when: letsencrypt_challenge_type == 'dns_01'
  ansible.builtin.include_tasks:
    file: "dns_01_cleanup.yml" 

- name: Configure nginx
  when: acme_configure_nginx
  ansible.builtin.include_tasks: nginx.yml
