---
- name: Create .well-known/acme-challenge directory
  ansible.builtin.file:
    path: >-
      {{ letsencrypt_http01_webroot }}/
      {{ r_acme_challenge['challenge_data'][letsencrypt_domain_name]['http-01']['resource'] | ansible.builtin.dirname }}
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Implement http-01 challenge files
  ansible.builtin.copy:
    content: "{{ r_acme_challenge['challenge_data'][letsencrypt_domain_name]['http-01']['resource_value'] }}"
    dest: "{{ letsencrypt_http01_webroot }}/{{ r_acme_challenge['challenge_data'][letsencrypt_domain_name]['http-01']['resource'] }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
