---
- name: Retrieve host metrics by organization
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    report_dest: "{{ playbook_dir }}/org_host_metrics_report.json" # Destination location for report
    report_mode: "0644" # Destination permissions for report

  roles:
    - role: ../roles/org_host_metrics # noqa role-name[path]
      vars:
        org_host_metrics_org_names:
          - Autodotes
          - Default

  tasks:
    - name: Publish report
      ansible.builtin.copy:
        content: "{{ org_host_metrics_report | to_nice_json(indent=2) }}"
        dest: "{{ report_dest }}"
        mode: "{{ report_mode }}"
