name: Publish collection

permissions:
  contents: write

on:
  workflow_dispatch:
    secrets:
      MY_PAH_TOKEN:
        description: 'API token for Private Automation Hub'
        required: false
      MY_GALAXY_TOKEN:
        description: 'API token for public Ansible Galaxy'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Install python requirements
        run: pip install ansible
          
      - name: substitute token for automation hub
        id: inject-tokens
        run: |
          cp ansible.cfg.publish ansible.cfg
          sed -i "s/my_pah_token/$MY_PAH_TOKEN/1" ansible.cfg
          sed -i "s/my_galaxy_token/$MY_GALAXY_TOKEN/1" ansible.cfg
        env:
          MY_PAH_TOKEN: ${{ secrets.MY_PAH_TOKEN }}
          MY_GALAXY_TOKEN: ${{ secrets.MY_GALAXY_TOKEN }}

      - name: tag commit
        id: tag-commit
        run: ./.github/scripts/increment-tag.sh
        shell: bash

      - name: Set version
        id: set-version
        run: |
          echo $NEW_VERSION
          sed -i "s/semantic_version/$NEW_VERSION/1" galaxy.yml
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}

      - name: Build collection
        id: build-collection
        run: ansible-galaxy collection build .

      # - name: Publish collection to Private Automation Hub
      #   id: publish-pah
      #   run: ansible-galaxy collection publish zjleblanc-utils-$NEW_VERSION.tar.gz -s pah
      #   env:
      #     NEW_VERSION: ${{ env.NEW_VERSION }}
        
      - name: Publish collection to Galaxy
        id: publish-galaxy
        run: ansible-galaxy collection publish zjleblanc-utils-$NEW_VERSION.tar.gz -s galaxy
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}